export default {
    // 通知
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_NOTIFICATIONS_AS_READ: 'MARK_NOTIFICATIONS_AS_READ',
    START_MORK_AS_READ: 'START_MORK_AS_READ',
    FINISH_MORK_AS_READ: 'FINISH_MORK_AS_READ',
    RECIVED_NOTIFICATIONS: 'RECIVED_NOTIFICATIONS',
    
    // 登录
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    // 头像设置
    CHANGE_AVATAR: 'CHANGE_AVATAR' ,

    // immutable练习
    ADD: 'ADD',
    DIV: 'DIV'
}