export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_NOTIFICATIONS_AS_READ: 'MARK_NOTIFICATIONS_AS_READ',
    START_MORK_AS_READ: 'START_MORK_AS_READ',
    FINISH_MORK_AS_READ: 'FINISH_MORK_AS_READ',
    RECIVED_NOTIFICATIONS: 'RECIVED_NOTIFICATIONS'
}